### ISSUE TITLE
About migrate php-framework from Yii2 to others

### ISSUE THREAD

**Issue by talentant** [yii2tech/illuminate#1]
> **Why switch from Yii2 to Laravel?**
> It is sad to admit, but Yii is outdated technology, which does not keep up with the modern trends....
> ...

@klimov-paul I totally agree with you, and I am also thinking about the same migration question recently. What do you think of [CakePHP](https://github.com/cakephp/cakephp) as a migration option?

**Comment by klimov-paul** [comment]
The actual framework choice depends on the individual, making it. Each person has his own preferences, needs and concerns.
At the present state Laravel is most popular PHP framework. [Laravel package](https://github.com/laravel/laravel/) has more then 50K stars at GitHub. So it is obvious choice for me.
As for CakePHP - it never impressed me. Personally, I would not use it.
Also keep in mind that in modern world open-source can not longer function as before. Each project, which is expected to be significant and popular, should have a financial foundation, it can not succeed using only volunteer work. Laravel is the project with solid commercial foundation.
