### ISSUE TITLE
How to move from yii advanced template to laravel?

### ISSUE THREAD

**Issue by lucasrothamel** [yii2tech/illuminate#2]
Hello,

I am planning transition from yii to laravel, and would like to ask:

How would you approach transition of a project originally written in the yii advanced template? We have three domains connected (backend, frontend and api) using the yii advanced template. Want to run it in laravel.

Thanks!
Lucas

**Comment by klimov-paul** [comment]
This is the matter of proper configuration.
You will need to register multiple route fallbacks with [YiiApplicationMiddleware](https://github.com/yii2tech/illuminate/blob/master/docs/start-installation.md#yii-application-middleware-) attached. One per each sub-domain you use. Follow [Laravel subdomain routing insrtuctions](https://laravel.com/docs/6.x/routing#route-group-subdomain-routing) for this.

```php
<?php
...
Route::domain('frontend.example.code')->any('{fallbackPlaceholder}', function () {
    abort(404);
})
    ->middleware(Yii2tech\Illuminate\Http\YiiApplicationMiddleware::class.':legacy/frontend/web/index.php')
    ->where('fallbackPlaceholder', '.*')
    ->fallback();

Route::domain('backend.example.code')->any('{fallbackPlaceholder}', function () {
    abort(404);
})
    ->middleware(Yii2tech\Illuminate\Http\YiiApplicationMiddleware::class.':legacy/backend/web/index.php')
    ->where('fallbackPlaceholder', '.*')
    ->fallback();

Route::domain('api.example.code')->any('{fallbackPlaceholder}', function () {
    abort(404);
})
    ->middleware(Yii2tech\Illuminate\Http\YiiApplicationMiddleware::class.':legacy/api/web/index.php')
    ->where('fallbackPlaceholder', '.*')
    ->fallback();
```
