### ISSUE TITLE
Di\Container::getIlluminateContainer() must implement interface

### ISSUE THREAD

**Issue by Orange-Men** [yii2tech/illuminate#3]
### What steps will reproduce the problem?
Uncomment:
```
'container' => [
  '__class' => Yii2tech\Illuminate\Yii\Di\Container::class,
],
```
in config/yii.php
### What do you get instead?
![image](https://user-images.githubusercontent.com/11768799/74922935-a1c05800-53d8-11ea-819d-2bf42276cafe.png)

P.s.
The same thing I've got with cache:
 
![image](https://user-images.githubusercontent.com/11768799/74923397-63776880-53d9-11ea-9118-a91a50e4fd03.png)

### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.1.0
| Laravel Framework Version | 6.16.0
| Yii Framework Version     | 2.0.32
| PHP version               | PHP 7.2.24
| Operating system          |ubuntu 18.04.3

**Comment by klimov-paul** [comment]
Resolved by commit 1c6a5ab579d0237e4cb98f0b3303cae0ca157857
