### ISSUE TITLE
Session bridge

### ISSUE THREAD

**Issue by Orange-Men** [yii2tech/illuminate#6]
Based: https://github.com/yii2tech/illuminate/issues/5
From docs:
> **Heads up!** usage of this component requires Yii application running within `\Illuminate\Session\Middleware\StartSession` middleware. Make sure it is running prior to `\Yii2tech\Illuminate\Http\YiiApplicationMiddleware` one.

How exactly it should achieve it?
Is move it from `$middlewareGroups['web']` to `$middleware` and do some manipulation with `$middlewarePriority` or ...?

My current `Kernel.php`:
```
protected $middleware = [
        \Illuminate\Session\Middleware\StartSession::class,
        ...
        \Yii2tech\Illuminate\Http\YiiApplicationMiddleware::class,
    ];

protected $middlewareGroups = [
        'web' => [
            ...
            // \Illuminate\Session\Middleware\StartSession::class,
            ...
        ],
            ...
    ];
protected $middlewarePriority = [
        \Illuminate\Session\Middleware\StartSession::class,
        ...
        \Yii2tech\Illuminate\Http\YiiApplicationMiddleware::class,
    ];
```

**Comment by klimov-paul** [comment]
Sorry, but I do not provide consulting regardless Laravel basic features.
Please refer to the [Laravel official documentation](https://laravel.com/docs), [Laracast](https://laracasts.com/) or other information source.
