### ISSUE TITLE
Feature tests. Unable to determine the request URI.

### ISSUE THREAD

**Issue by Orange-Men** [yii2tech/illuminate#7]
_Error:
yii\base\InvalidConfigException: Unable to determine the request URI. in project/vendor/yiisoft/yii2/web/Request.php on line 1059_
### What steps will reproduce the problem?
It looks like the `$_SERVER['REQUEST_URI']` is empty after passing of the request to Yii2 side.

tests/Feature/ExampleTest.php
```
...
public function testBasicTest()
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
...
```
### Additional info
If set `$_SERVER['REQUEST_URI']` manually all works fine.
tests/TestCase.php
```
abstract class TestCase extends BaseTestCase
{
    //use CreatesApplication;

    public function createApplication()
    {
        $_SERVER['SCRIPT_FILENAME'] = dirname(__DIR__) . '/public/index.php';
        $_SERVER['SCRIPT_NAME'] = '/index.php';
        $_SERVER['REQUEST_URI'] = '/';

        $app = require __DIR__ . '/../bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        return $app;
    }
}
```

| Q                         | A
| ------------------------- | ---
| This Package Version      | dev-master
| Laravel Framework Version | 6.18.19
| Yii Framework Version     | 2.0.35
| PHP version               | 7.4.7
| Operating system          | Ubuntu 18.04.4 LTS

**Comment by klimov-paul** [comment]
Resolved by commit ddee1e71caf26ee4194162fccc9f3f6260fb9f0a
