### ISSUE TITLE
Question Could you provide any sample project with basic yii2 template conversion?

### ISSUE THREAD

**Issue by i-internet** [yii2tech/illuminate#9]
I have been working with yii2 since 3 years now and there is a project which is very important and I have to migrate it for my client. I can convince him to migrate to larval but before that I would like to be very sure of that how I'm gonna plan everything.

Could you please provide basic yii2 template conversion code with laravel please?

It will be really helpful for me to continue with new framework and learn more about both yii2 and laravel.

Yii2 is something which I'm comfortable with and it's so robust that I can't deny the fact that it is still working fine and giving us a class performance.

But due to lack of latest modules I do have to move on.

Thanks

**Comment by klimov-paul** [comment]
> Could you please provide basic yii2 template conversion code with laravel please?

Sorry, but I can not.
If you follow the [docs](docs/README.md) step by step, you should find enough info to migrate basic yii2 template yourself.

> It will be really helpful for me to continue with new framework and learn more about both yii2 and laravel.

Sorry, but I do not run educational courses here.
Please refer to the [Laravel official documentation](https://laravel.com/docs), [Laracast](https://laracasts.com/) or other information source.
